services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_collector_app
    ports:
      - '3333:3333'
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - db
    volumes:
      - app_data:/data
    command:
      ['./scripts/wait-for-it.sh', 'db:5432', '--', 'npm', 'run', 'start:prod']

  db:
    image: bitnami/postgresql:13.16.0
    container_name: task_collector_db
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task_collector
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -h 127.0.0.1 -d task_collector']
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local
  postgresql_data:
    driver: local
